BEGIN TRANSACTION;


DROP TABLE IF EXISTS rt1;

CREATE TABLE rt1
  (idrt1   INTEGER	PRIMARY KEY AUTOINCREMENT,
   NomPromo TEXT    NOT NULL,
   Prenom	TEXT	NOT NULL,
   Nom      TEXT    NOT NULL
  );

INSERT INTO rt1 VALUES('0',  'rt1', 'Noah', 'Claudel--Ruiellet');


DROP TABLE IF EXISTS Notesrt1;

CREATE TABLE Notesrt1
  (idNotert1	INTEGER	PRIMARY KEY,
   idrt1  INTEGER NOT NULL,
   Note	  INTEGER NULL,
   Coef	    INTEGER NULL,
   FOREIGN KEY (idrt1) REFERENCES rt1 (idrt1)
  );

COMMIT;